# Generated by Django 5.2.8 on 2026-04-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop_app", "0005_productattributevalue"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
