# Generated by Django 5.2.8 on 2026-04-13 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0007_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_amazing',
            field=models.BooleanField(default=False),
        ),
    ]
