# Generated by Django 5.2.8 on 2026-04-14 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0016_alter_productimage_image_alter_productimage_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributevalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_attribute_values', to='shop_app.product'),
        ),
    ]
