# Generated by Django 5.2.8 on 2026-04-14 15:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shop_app", "0019_order_is_canceled"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="is_canceled",
        ),
    ]
