# Generated by Django 5.2.8 on 2026-04-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='قابل نمایش'),
        ),
    ]
