# Generated by Django 6.0.4 on 2026-07-20 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_app', '0002_alter_image_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد فیلد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی فیلد')),
                ('is_active', models.BooleanField(default=True, verbose_name='قابل نمایش')),
                ('is_main_settings', models.BooleanField(default=True)),
                ('header_phone', models.CharField()),
                ('header_email', models.EmailField(max_length=254)),
                ('header_logo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='header_logo', to='core_app.image')),
            ],
            options={
                'db_table': 'main_settings',
            },
        ),
    ]
