# Generated by Django 5.2.8 on 2025-11-30 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernotification',
            options={'ordering': ('id',)},
        ),
    ]
