# Generated by Django 5.2.8 on 2025-11-26 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='father_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='نام پدر'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth_app.image', verbose_name='عکس پروفایل'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='شماره پلاک'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='nation_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='نام خوانوادگی'),
        ),
    ]
