# Generated by Django 5.2.8 on 2025-11-30 12:26

import auth_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLogVerifyPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='حذف')),
                ('phone', models.CharField(max_length=15, validators=[auth_app.validators.PhoneNumberValidator()], verbose_name='شماره همراه')),
                ('is_accept', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'auth_request_log_verify_phone',
            },
        ),
    ]
