# Generated by Django 5.2.8 on 2025-11-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdocument',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
