# Generated by Django 5.2.8 on 2025-11-29 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_driver_father_name_alter_driver_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='شماره پلاک'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='nation_code',
            field=models.CharField(blank=True, max_length=10, unique=True, verbose_name='کد ملی'),
        ),
    ]
