# Generated by Django 5.2.8 on 2025-12-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_usernotification_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='nation_code',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='کد ملی'),
        ),
    ]
