# Generated by Django 5.2.8 on 2025-11-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_requestlogverifyphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlogverifyphone',
            name='ip_address',
            field=models.GenericIPAddressField(null=True, verbose_name='ای اپی کاربر'),
        ),
    ]
