# Generated by Django 5.2.8 on 2025-11-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_requestlogverifyphone_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlogverifyphone',
            name='user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='شناسه مرورگر'),
        ),
    ]
