# Generated by Django 5.2.8 on 2025-11-29 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_driver_license_number_alter_driver_nation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverdocument',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='image_driver_docs', to='auth_app.image', verbose_name='عکس'),
        ),
    ]
