# Generated by Django 5.2.8 on 2025-12-01 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_driver_nation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='license_number',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='شماره پلاک'),
        ),
    ]
