# Generated by Django 5.2.8 on 2025-11-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_requestlogverifyphone_user_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestlogverifyphone',
            name='is_accept',
            field=models.BooleanField(default=False, verbose_name='تایید شده!'),
        ),
    ]
