# Generated by Django 5.2.8 on 2025-12-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_driver_license_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_passenger',
            field=models.BooleanField(db_default=True, default=True, verbose_name='ایا مسافر هست!'),
        ),
    ]
