# Generated by Django 5.2.8 on 2025-11-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_requestlogverifyphone_is_accept'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlogverifyphone',
            name='behavior_type',
            field=models.CharField(choices=[('multiple_failed_attempts', 'تلاش\u200cهای ناموفق متعدد'), ('rapid_requests', 'درخواست\u200cهای سریع'), ('suspicious_location', 'موقعیت جغرافیایی مشکوک'), ('unusual_activity', 'فعالیت غیرعادی'), ('brute_force', 'حمله brute force'), ('account_takeover', 'تصاحب حساب'), ('credential_stuffing', 'پرکردن اعتبار')], max_length=50, null=True, verbose_name='نوع رفتار مشکوک'),
        ),
    ]
