# Generated by Django 5.2.8 on 2025-11-30 14:20

import auth_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_requestlogverifyphone_behavior_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='حذف')),
                ('phone', models.CharField(max_length=15, validators=[auth_app.validators.PhoneNumberValidator()], verbose_name='شماره همراه')),
                ('ip_address', models.GenericIPAddressField(null=True, verbose_name='ای اپی کاربر')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='شناسه مرورگر')),
                ('behavior_type', models.CharField(choices=[('multiple_failed_attempts', 'تلاش\u200cهای ناموفق متعدد'), ('rapid_requests', 'درخواست\u200cهای سریع'), ('suspicious_location', 'موقعیت جغرافیایی مشکوک'), ('unusual_activity', 'فعالیت غیرعادی'), ('brute_force', 'حمله brute force'), ('account_takeover', 'تصاحب حساب'), ('credential_stuffing', 'پرکردن اعتبار')], max_length=50, null=True, verbose_name='نوع رفتار مشکوک')),
            ],
            options={
                'db_table': 'auth_request_log_verify_phone',
            },
        ),
        migrations.DeleteModel(
            name='RequestLogVerifyPhone',
        ),
    ]
