# Generated by Django 5.2.8 on 2025-12-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_alter_driver_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='note',
            field=models.TextField(blank=True, null=True, verbose_name='یادداشت'),
        ),
    ]
