# Generated by Django 5.2.8 on 2025-11-30 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0007_requestlog_delete_requestlogverifyphone'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='requestlog',
            table='auth_request_log',
        ),
    ]
