# Generated by Django 6.0.4 on 2026-07-20 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_initial'),
        ('trip_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='passenger_trips', to='auth_app.passenger', verbose_name='مسافر'),
        ),
    ]
