# Generated by Django 5.2.8 on 2026-04-03 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_driver_car_name_alter_driverdocument_doc_type'),
        ('trip_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='passenger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='auth_app.passenger', verbose_name='مسافر'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='phone_reserve_for_other',
            field=models.CharField(blank=True, null=True, verbose_name='شماره تماس رزور کننده دیگر'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='price_per_seat',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='قیمت کل'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('confirmed', 'تایید شده'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده'), ('reserve', 'رزور سفر')], default='pending', max_length=20, verbose_name='وضعیت سفر'),
        ),
    ]
