# Generated by Django 6.0.7 on 2026-07-27 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0003_mainsettings"),
        ("trip_app", "0002_alter_trip_passenger"),
    ]

    operations = [
        migrations.CreateModel(
            name="TripType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ ایجاد فیلد"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="تاریخ اخرین بروزرسانی فیلد"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="قابل نمایش"),
                ),
                ("trip_name", models.CharField(max_length=255)),
                (
                    "trip_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trip_image",
                        to="core_app.image",
                    ),
                ),
            ],
            options={
                "db_table": "trip_type",
            },
        ),
    ]
