# Generated by Django 6.0.7 on 2026-07-27 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core_app", "0003_mainsettings"),
        ("trip_app", "0003_triptype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="triptype",
            name="trip_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trip_image",
                to="core_app.image",
            ),
        ),
    ]
