# Generated by Django 6.0.7 on 2026-07-28 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trip_app", "0004_alter_triptype_trip_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="from_address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="to_address",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="trip",
            name="trip_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="trip_app.triptype",
            ),
        ),
    ]
