# Generated by Django 6.0.7 on 2026-07-28 09:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trip_app", "0006_remove_trip_number_of_passenger"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trip",
            name="driver",
        ),
    ]
