# Generated by Django 6.0.7 on 2026-07-28 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0008_tripreservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='price_per_seat',
        ),
    ]
