# Generated by Django 6.0.7 on 2026-07-31 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0011_trip_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripprice',
            name='trip',
        ),
    ]
