# Generated by Django 6.0.7 on 2026-07-31 18:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trip_app", "0012_remove_tripprice_trip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tripprice",
            name="price_per_minute",
        ),
        migrations.RemoveField(
            model_name="tripprice",
            name="total_price",
        ),
    ]
