# Generated by Django 6.0.7 on 2026-07-31 18:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("trip_app", "0014_tripprice_night_factor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tripprice",
            name="night_factor",
        ),
    ]
