# Generated by Django 6.0.7 on 2026-07-31 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0016_alter_tripprice_traffic_factor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripprice',
            name='base_price',
        ),
    ]
