# Generated by Django 6.0.7 on 2026-07-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trip_app", "0017_remove_tripprice_base_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "در انتظار"),
                    ("confirmed", "تایید شده"),
                    ("completed", "تکمیل شده"),
                    ("cancelled", "لغو شده"),
                    ("reserve", "رزور سفر"),
                ],
                default="pending",
                max_length=20,
                verbose_name="وضعیت سفر",
            ),
        ),
    ]
