# Generated by Django 6.0.7 on 2026-08-01 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip_app', '0018_alter_trip_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='from_lat',
            field=models.DecimalField(decimal_places=15, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='from_lng',
            field=models.DecimalField(decimal_places=15, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='to_lat',
            field=models.DecimalField(decimal_places=15, max_digits=17, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='to_lng',
            field=models.DecimalField(decimal_places=15, max_digits=17, null=True),
        ),
    ]
