# Generated by Django 5.2.8 on 2026-04-08 19:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد فیلد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی فیلد')),
                ('is_active', models.BooleanField(default=True, verbose_name='قابل نمایش')),
                ('brand_name', models.CharField(max_length=100, unique=True, verbose_name='برند ماشین')),
            ],
            options={
                'db_table': 'car_brand',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد فیلد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی فیلد')),
                ('nation_code', models.CharField(max_length=10, null=True, unique=True, verbose_name='کد ملی')),
                ('father_name', models.CharField(blank=True, max_length=50, verbose_name='نام پدر')),
                ('license_number', models.CharField(max_length=20, null=True, unique=True, verbose_name='شماره پلاک')),
                ('verification_status', models.CharField(choices=[('submitted', 'ارسال شده'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('created', 'ایجاد شده')], default='created', max_length=10, verbose_name='تایید پروفایل')),
                ('disable_account', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'auth_driver_profile',
            },
        ),
        migrations.CreateModel(
            name='DriverCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد فیلد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی فیلد')),
                ('is_active', models.BooleanField(default=True, verbose_name='قابل نمایش')),
            ],
            options={
                'db_table': 'auth_driver_car',
            },
        ),
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد فیلد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی فیلد')),
                ('is_active', models.BooleanField(default=True, verbose_name='قابل نمایش')),
                ('doc_type', models.CharField(choices=[('id_front', 'جلوی کارت شناسایی'), ('id_back', 'پشت کارت شناسایی'), ('car_front', 'جلوی کارت خودرو'), ('car_back', 'پشت کارت خودرو'), ('insurance', 'بیمه'), ('identity_verify', 'تایید هویت'), ('fuel_card', 'کارت سوخت')], max_length=15, verbose_name='نوع مدارک')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده!')),
                ('verifier_note', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
            ],
            options={
                'db_table': 'auth_driver_document',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد فیلد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی فیلد')),
                ('disable_account', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'auth_passenger',
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد فیلد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی فیلد')),
                ('is_active', models.BooleanField(default=True, verbose_name='قابل نمایش')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='متن')),
            ],
            options={
                'db_table': 'auth_user_notification',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='شماره تلفن')),
                ('is_verify_phone', models.BooleanField(default=False, verbose_name='شماره تایید شده!')),
                ('is_passenger', models.BooleanField(db_default=True, default=True, verbose_name='ایا مسافر هست!')),
                ('is_driver', models.BooleanField(default=False, verbose_name='ایا راننده هست!')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='نام خوانوادگی')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد فیلد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی فیلد')),
                ('is_active', models.BooleanField(default=True, verbose_name='قابل نمایش')),
                ('model_name', models.CharField(max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth_app.carbrand', verbose_name='برند ماشین')),
            ],
            options={
                'db_table': 'car_model',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد فیلد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی فیلد')),
                ('is_active', models.BooleanField(default=True, verbose_name='قابل نمایش')),
                ('name', models.CharField(max_length=100, verbose_name='نام ماشین')),
                ('year', models.PositiveIntegerField(choices=[(1300, 1300), (1301, 1301), (1302, 1302), (1303, 1303), (1304, 1304), (1305, 1305), (1306, 1306), (1307, 1307), (1308, 1308), (1309, 1309), (1310, 1310), (1311, 1311), (1312, 1312), (1313, 1313), (1314, 1314), (1315, 1315), (1316, 1316), (1317, 1317), (1318, 1318), (1319, 1319), (1320, 1320), (1321, 1321), (1322, 1322), (1323, 1323), (1324, 1324), (1325, 1325), (1326, 1326), (1327, 1327), (1328, 1328), (1329, 1329), (1330, 1330), (1331, 1331), (1332, 1332), (1333, 1333), (1334, 1334), (1335, 1335), (1336, 1336), (1337, 1337), (1338, 1338), (1339, 1339), (1340, 1340), (1341, 1341), (1342, 1342), (1343, 1343), (1344, 1344), (1345, 1345), (1346, 1346), (1347, 1347), (1348, 1348), (1349, 1349), (1350, 1350), (1351, 1351), (1352, 1352), (1353, 1353), (1354, 1354), (1355, 1355), (1356, 1356), (1357, 1357), (1358, 1358), (1359, 1359), (1360, 1360), (1361, 1361), (1362, 1362), (1363, 1363), (1364, 1364), (1365, 1365), (1366, 1366), (1367, 1367), (1368, 1368), (1369, 1369), (1370, 1370), (1371, 1371), (1372, 1372), (1373, 1373), (1374, 1374), (1375, 1375), (1376, 1376), (1377, 1377), (1378, 1378), (1379, 1379), (1380, 1380), (1381, 1381), (1382, 1382), (1383, 1383), (1384, 1384), (1385, 1385), (1386, 1386), (1387, 1387), (1388, 1388), (1389, 1389), (1390, 1390), (1391, 1391), (1392, 1392), (1393, 1393), (1394, 1394), (1395, 1395), (1396, 1396), (1397, 1397), (1398, 1398), (1399, 1399), (1400, 1400), (1401, 1401), (1402, 1402), (1403, 1403), (1404, 1404), (1405, 1405), (1406, 1406), (1407, 1407), (1408, 1408), (1409, 1409)], verbose_name='سال تولید')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth_app.carbrand', verbose_name='برند')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth_app.carmodel', verbose_name='مدل')),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
