# Generated by Django 5.2.8 on 2026-04-03 12:26

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='خوانوادگی')),
                ('nation_code', models.CharField(max_length=10, null=True, unique=True, verbose_name='کد ملی')),
                ('father_name', models.CharField(blank=True, max_length=50, verbose_name='نام پدر')),
                ('license_number', models.CharField(max_length=20, null=True, unique=True, verbose_name='شماره پلاک')),
                ('verification_status', models.CharField(choices=[('submitted', 'ارسال شده'), ('approved', 'تایید شده'), ('rejected', 'رد شده')], default='submitted', max_length=10, verbose_name='تایید پروفایل')),
                ('note', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
            ],
            options={
                'db_table': 'auth_driver_profile',
            },
        ),
        migrations.CreateModel(
            name='DriverDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('doc_type', models.CharField(choices=[('id_front', 'جلوی کارت شناسایی'), ('id_back', 'پشت کارت شناسایی'), ('car_front', 'جلوی خودرو'), ('car_back', 'پشت خودرو'), ('insurance', 'بیمه'), ('identity_verif', 'تایید هویت')], max_length=50, verbose_name='نوع مدارک')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده!')),
                ('verifier_note', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
            ],
            options={
                'db_table': 'auth_driver_document',
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='نام خوانوادگی')),
            ],
            options={
                'db_table': 'auth_passenger',
            },
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='متن')),
            ],
            options={
                'db_table': 'auth_user_notification',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='شماره تلفن')),
                ('is_verify_phone', models.BooleanField(default=False, verbose_name='شماره تایید شده!')),
                ('is_passenger', models.BooleanField(db_default=True, default=True, verbose_name='ایا مسافر هست!')),
                ('is_driver', models.BooleanField(default=False, verbose_name='ایا راننده هست!')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
