# Generated by Django 6.0.7 on 2026-07-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth_app", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_developer",
            field=models.BooleanField(default=False, verbose_name="توسعه دهنده"),
        ),
    ]
