# Generated by Django 5.2.8 on 2026-04-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_remove_driver_first_name_remove_driver_last_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='driverdocument',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='قابل نمایش'),
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='قابل نمایش'),
        ),
    ]
