# Generated by Django 5.2.8 on 2026-04-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_remove_driver_is_active_remove_passenger_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverdocument',
            name='doc_type',
            field=models.CharField(choices=[('id_front', 'جلوی کارت شناسایی'), ('id_back', 'پشت کارت شناسایی'), ('car_front', 'جلوی خودرو'), ('car_back', 'پشت خودرو'), ('insurance', 'بیمه'), ('identity_verify', 'تایید هویت')], max_length=15, verbose_name='نوع مدارک'),
        ),
    ]
