# Generated by Django 5.2.8 on 2026-04-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_driverdocument_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='car_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نام ماشین'),
        ),
        migrations.AlterField(
            model_name='driverdocument',
            name='doc_type',
            field=models.CharField(choices=[('id_front', 'جلوی کارت شناسایی'), ('id_back', 'پشت کارت شناسایی'), ('car_front', 'جلوی کارت خودرو'), ('car_back', 'پشت کارت خودرو'), ('insurance', 'بیمه'), ('identity_verify', 'تایید هویت'), ('fuel_card', 'کارت سوخت')], max_length=15, verbose_name='نوع مدارک'),
        ),
    ]
