# Generated by Django 5.2.8 on 2026-04-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0006_driver_car_name_alter_driverdocument_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='disable_account',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passenger',
            name='disable_account',
            field=models.BooleanField(default=False),
        ),
    ]
