# Generated by Django 5.2.8 on 2026-04-04 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0009_car_created_at_car_is_active_car_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='name',
            new_name='model_name',
        ),
    ]
