# Generated by Django 5.2.8 on 2026-04-04 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0011_alter_car_created_at_alter_car_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='note',
        ),
    ]
