# Generated by Django 5.2.8 on 2026-04-04 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0012_remove_driver_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='car',
        ),
        migrations.CreateModel(
            name='DriverCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد فیلد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ اخرین بروزرسانی فیلد')),
                ('is_active', models.BooleanField(default=True, verbose_name='قابل نمایش')),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='auth_app.car', verbose_name='ماشین')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth_app.driver', verbose_name='راننده')),
            ],
            options={
                'db_table': 'auth_driver_car',
            },
        ),
    ]
