# Generated by Django 5.2.8 on 2026-04-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0013_remove_driver_car_drivercar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverdocument',
            old_name='profile',
            new_name='driver',
        ),
    ]
